# Generated by Django 2.1.2 on 2019-03-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaID', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('positionX', models.IntegerField(default=0)),
                ('positionY', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculoID', models.IntegerField(default=0)),
                ('placa', models.CharField(max_length=100)),
                ('cargaMudanza', models.BooleanField()),
                ('portaBebe', models.BooleanField()),
                ('portaAnimal', models.BooleanField()),
                ('positionX', models.IntegerField(default=0)),
                ('positionY', models.IntegerField(default=0)),
            ],
        ),
    ]
